### PR TITLE
Config and version

### PR DESCRIPTION
**Pull request by tkishel**
## Description

add a cspm version check and improve config mapping between cli and api

## Motivation and Context

Question on Slack

## How Has This Been Tested?

Manual, Flake8

## Types of changes

- New feature (non-breaking change which adds functionality)

## Checklist

- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes if appropriate.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by tkishel** [comment]
That is probably because of this:

https://github.com/PaloAltoNetworks/prismacloud-cli/pull/69#issuecomment-1170483296

**Comment by tkishel** [comment]
But the same test passes locally:

```
M-C02ZQM2XMD6M:~ tkishel$ PC_SAAS_API_ENDPOINT=api.prismacloud.io PC_COMPUTE_API_ENDPOINT="" PC_ACCESS_KEY=f323607c-9523-46ef-b3d4-5385712c470d PC_SECRET_KEY=05jU6FMC/MWIrxAyYbQPdCxMuN8= pc --config environment -vv check
2022-07-14 08:09:45 M-C02ZQM2XMD6M root[68091] INFO Running prismacloud-cli version 0.4.41 / prismacloud-api version 4.0.8
2022-07-14 08:09:45 M-C02ZQM2XMD6M root[68091] DEBUG Reading configuration from environment
2022-07-14 08:09:45 M-C02ZQM2XMD6M root[68091] DEBUG Environment variable found: PC_SAAS_API_ENDPOINT: api.prismacloud.io
2022-07-14 08:09:45 M-C02ZQM2XMD6M root[68091] DEBUG Environment variable found: PC_COMPUTE_API_ENDPOINT: 
2022-07-14 08:09:45 M-C02ZQM2XMD6M root[68091] DEBUG Environment variable found: PC_ACCESS_KEY: f32********************************
2022-07-14 08:09:45 M-C02ZQM2XMD6M root[68091] DEBUG Environment variable found: PC_SECRET_KEY: 05j************************
2022-07-14 08:09:45 M-C02ZQM2XMD6M root[68091] DEBUG Configuration read from environment
2022-07-14 08:09:45 M-C02ZQM2XMD6M urllib3.connectionpool[68091] DEBUG Starting new HTTPS connection (1): api.prismacloud.io:443
2022-07-14 08:09:45 M-C02ZQM2XMD6M urllib3.connectionpool[68091] DEBUG https://api.prismacloud.io:443 "GET /meta_info HTTP/1.1" 200 None
2022-07-14 08:09:45 M-C02ZQM2XMD6M root[68091] DEBUG Calling API Endpoint (GET): check
2022-07-14 08:09:45 M-C02ZQM2XMD6M urllib3.connectionpool[68091] DEBUG Starting new HTTPS connection (1): api.prismacloud.io:443
2022-07-14 08:09:45 M-C02ZQM2XMD6M urllib3.connectionpool[68091] DEBUG https://api.prismacloud.io:443 "GET /check HTTP/1.1" 200 None
2022-07-14 08:09:45 M-C02ZQM2XMD6M root[68091] DEBUG Settings: maximum width: 25
2022-07-14 08:09:45 M-C02ZQM2XMD6M root[68091] DEBUG Settings: maximum number of rows: 1000000
2022-07-14 08:09:45 M-C02ZQM2XMD6M root[68091] DEBUG Settings: maximum number of columns: 7
2022-07-14 08:09:45 M-C02ZQM2XMD6M root[68091] DEBUG Settings: maximum number of levels to flatten: 2
2022-07-14 08:09:45 M-C02ZQM2XMD6M root[68091] DEBUG Using json_normalize() data
2022-07-14 08:09:45 M-C02ZQM2XMD6M root[68091] DEBUG Flatten nested json
message
----------------------------
hello from the other side...
```

**Comment by tkishel** [comment]
I've added the secrets to my fork, could you rerun that test workflow to see if it picks up my secrets?

If that does not work, then we may need to use environments and environment secrets.

**Review by SimOnPanw — APPROVED** [review]
Lgtm

**Comment by SimOnPanw** [comment]
LGTM

**Comment by SimOnPanw** [comment]
Release into v.04.42

**Pull request merged**
